In [32]:
import tensorflow as tf
import numpy as np

In [33]:
# Checking the version of the tensorflow  we will used tensorflow v2 here 
print(tf.version)

<module 'tensorflow._api.v2.version' from '/Users/siddharthaganguli/Desktop/tensorflow/myenv/lib/python3.9/site-packages/tensorflow/_api/v2/version/__init__.py'>


**Let's Check some basic things on Tensorflow**

Tensorflow = Tensor + Flow 

Tensor: It Represents a multidimensional array 

**Each Tensor has a dtype and shape**

Data-type(dtype): int8,int16,int32,int64,float16,float32,float64,string etc..

Flow: Refers to the graph of operations applied to the tensors. Operations are organized into graph to compute the result 

**Types of Tensors**<br>
**Variable()**<br>
**Constant()**<br>
**Placeholder()**<br>
**SparseTensor()**<br>

Properties of tensor: 

1: A unique name {in default the framework continuously generate some unique name for every tensor}

2: A dimension

3: a data type 

In [11]:
# Constant Tensor : This represents a constant ot immutable value that cannot be changed 
# tf.constant(value , dtype, name="")
pi=tf.constant(3.1415,dtype='float64',name='pi_value')

# also we can define the datatype like this way
pi=tf.constant(3.1415,tf.float64)

print(pi)

# We can also use for string, int or any other datatype 
name=tf.constant("Rik Ganguli",name='My_Name')
name=tf.constant(["Rik"],tf.string)
print(name)

tf.Tensor(3.1415, shape=(), dtype=float64)
tf.Tensor([b'Rik'], shape=(1,), dtype=string)


**Rank And Degree of a Tensor**

In [13]:
rank1_Tensor=tf.Variable(['Test'],tf.string)
rank2_Tensor=tf.Variable([['Apple','Mango'],['Banana','Grapes']])

print(f"the rank of rank1_Tensor is {tf.rank(rank1_Tensor)}")
print(f"the rank of rank2_Tensor is {tf.rank(rank2_Tensor)}")

the rank of rank1_Tensor is 1
the rank of rank2_Tensor is 2


**Shape of Tensor** :
The shape of a tensor is simply the number of elements that exist in each dimension.

In [15]:
rank2_Tensor.shape

TensorShape([2, 2])

The first number (2) represents the number of rows

The second number (2) represents the number of elements in each row (columns)

**[  ['Apple', 'Mango'],**<br> 
  **['Banana', 'Grapes']**
**]**

Try to Changing  the Shape of the Tensor

In [31]:
tensor1=tf.ones([1,2,3],tf.int32)
print(tensor1)

tf.Tensor(
[[[1 1 1]
  [1 1 1]]], shape=(1, 2, 3), dtype=int32)


1: The tensor has 1 "block" or set of matrices. This means there is a single 3D array.<br>
2: Each block has 2 rows.<br>
3: Each row has 3 elements.<br>

Note::<br>
The number of values stored in a tensor is the product of the dimensions of its shape. If the shape is [a, b, c], the total number of values is:<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;a × b × c {suppose for this example having [1,2,3]shape so 1x2x3=6 value makimum store }


In [35]:
tensor2=tf.reshape(tensor1,[2,3,1],tf.int32)
print(tensor2)

tf.Tensor(
[[[1]
  [1]
  [1]]

 [[1]
  [1]
  [1]]], shape=(2, 3, 1), dtype=int32)


In [30]:
tensor3=tf.reshape(tensor1,[3,-1])
tensor4=tf.reshape(tensor2,[3,-1])
print(tensor3)
print(tensor4)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


**Explanation of [3, -1]** <br>
3: This specifies that the reshaped tensor should have 3 rows.<br>
-1: This is a special value in TensorFlow (and also in NumPy) that tells TensorFlow to automatically calculate the size of that dimension based on the total number of elements<br>
[TensorFlow will determine how many columns are needed]

Total elements=rows×columns<br>
6=3×c [6 meaning we know tenor2 having maximum 6 value storing capacity]

**CALCULATION** ::
Original tensor (tensor1) had the shape [1, 2, 3], which stored 6 values (calculated as 1×2×3=6) <br>
Reshaped tensor (tensor2) has the new shape [2, 3, 1]. To calculate the total number of values in this reshaped tensor: Total values=2×3×1=6

To find out how many columns (c) are needed, you can use the formula:<br>Total elements=rows×columns6=3×𝑐
<br>Total elements=rows×columns
6=3×c<br>
c=6/3=2<br>
So the shape will be [3, 2], meaning it has 3 rows and 2 columns


Suppose we have a tensor with 7 elements and you want to reshape it to have 3 rows
so now how to calculate it 


In [38]:
tensor = tf.Variable([1, 2, 3, 4, 5, 6, 7])  # Original tensor with 7 elements
padded_tensor = tf.pad(tensor, [[0, 2]], constant_values=0) #adding two zeroes for calculation now the shape is 9
print(padded_tensor)

tf.Tensor([1 2 3 4 5 6 7 0 0], shape=(9,), dtype=int32)


9=3×c <br>
⟹c= 3/9=3

**Slicing Tensors**

In [44]:
# Creating a 2D tensor
matrix = [[1,2,3,4,5],
          [6,7,8,9,10],
          [11,12,13,14,15],
          [16,17,18,19,20]]

# creating tensor of it 
matrix_tensor=tf.Variable(matrix,tf.int32)
print(matrix_tensor)
print(f"Rank of this tensor is {tf.rank(matrix_tensor)}")

<tf.Variable 'Variable:0' shape=(4, 5) dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]], dtype=int32)>
Rank of this tensor is 2


In [51]:
# Now lets select some different rows and columns from our tensor

# Accessing a Single Element
# Syntax: tensor[row, col]
#  Access the element in the 1st row and 2nd column (0-based index)
third_element=matrix_tensor[0, 1]
print(f"Third element of this matrix_tensor is {third_element}")

Printing the first two row  of this matrix_tensor is [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Third element of this matrix_tensor is 2


In [59]:
# Accessing a Row:
# Syntax: tensor[row_index, :]
row = matrix_tensor[1,:]
print(f"Printing the 2nd row of this matrix_tensor is {row}")

Printing the 2nd row of this matrix_tensor is [ 6  7  8  9 10]


In [57]:
# Accessing a Column
# Syntax: tensor[:, col_index]
col = matrix_tensor[:, 2]  # Output: [3, 8, 13, 18]
print(col)


tf.Tensor([ 3  8 13 18], shape=(4,), dtype=int32)


In [58]:
# Accessing a Submatrix (Slicing)
# Syntax: tensor[start_row:end_row, start_col:end_col]
submatrix = matrix_tensor[1:3, 2:5] 
print(submatrix)

tf.Tensor(
[[ 8  9 10]
 [13 14 15]], shape=(2, 3), dtype=int32)


In [61]:
# Accessing a Range of Rows
# Syntax: tensor[start_row:end_row, :]
rows = matrix_tensor[2:4, :]  # Output: [[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]
print(rows)

tf.Tensor(
[[11 12 13 14 15]
 [16 17 18 19 20]], shape=(2, 5), dtype=int32)


In [63]:
# Accessing a Range of Columns:
# Syntax: tensor[:, start_col:end_col]
cols = matrix_tensor[:, 1:4]  # Output: [[2, 3, 4], [7, 8, 9], [12, 13, 14], [17, 18, 19]]
print(cols)

tf.Tensor(
[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]], shape=(4, 3), dtype=int32)


***Using Negative Indices:***

In [64]:
# Negative indices count from the end of the matrix.
# Example: Access the last row
last_row = matrix_tensor[-1, :]  # Output: [16, 17, 18, 19, 20]
print(last_row)

tf.Tensor([16 17 18 19 20], shape=(5,), dtype=int32)


In [65]:
# Step Slicing:
# Syntax: tensor[start:end:step]
every_second_row = matrix_tensor[::2, :]  # Output: [[1, 2, 3, 4, 5], [11, 12, 13, 14, 15]]
print(every_second_row)

tf.Tensor(
[[ 1  2  3  4  5]
 [11 12 13 14 15]], shape=(2, 5), dtype=int32)


**Accessing Specific Rows and Columns:**

In [ ]:
# You can also specify lists of indices.
# Syntax: tensor[[row_indices], [col_indices]]
specific_elements = matrix_tensor[[0, 2, 3], [1, 3, 0]]  # Output: [2, 14, 16]


**Boolean Indexing:**

In [66]:
# we can slice using a condition.
bool_mask = matrix_tensor > 10
greater_than_10 = tf.boolean_mask(matrix_tensor, bool_mask) 
print(greater_than_10)

tf.Tensor([11 12 13 14 15 16 17 18 19 20], shape=(10,), dtype=int32)


***Summary of Slicing Techniques*** <br>
**Access a single element:**&nbsp;&nbsp;matrix_tensor[row, col]<br>
**Access a row:** &nbsp;&nbsp;matrix_tensor[row_index, :]<br>
**Access a column:** &nbsp;&nbsp;matrix_tensor[:, col_index]<br>
**Access a submatrix:** &nbsp;&nbsp;matrix_tensor[start_row:end_row, start_col:end_col]<br>
**Access rows:** &nbsp;&nbsp;matrix_tensor[start_row:end_row, :]<br>
**Access columns:** &nbsp;&nbsp;matrix_tensor[:, start_col:end_col]<br>
**Negative indices:** &nbsp;&nbsp;matrix_tensor[-1, :]<br>
**Step slicing:** &nbsp;&nbsp;matrix_tensor[::2, :]<br>
**Specific rows and columns:** &nbsp;&nbsp;matrix_tensor[[row_indices], [col_indices]]<br>
**Boolean indexing:** &nbsp;&nbsp;tf.boolean_mask(matrix_tensor, bool_mask)<br>